server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/springboot-ktforum?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
    # Uncomment the following line if you want to see SQL queries in logs
    # show-sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      repositories:
        enabled: false

    elasticsearch:
      repositories:
        enabled: false

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}

  session:
    store-type: redis
    redis:
      namespace: spring:sessio2

  cache:
    type: redis
    redis:
      namespace: app:cache

jwt:
  valid-access-token-duration: 6000000
  valid-refresh-token-duration: 60000000
  refreshable-duration: 240000

cookie:
  access-token-name: accessToken
  max-age-default-duration: 3600
  max-age-remember-me-duration: 7200

openapi:
  dev-url: http://localhost:8080

image:
  url:
    admin: https://res.cloudinary.com/dk7o7rlks/image/upload/v1725080957/kt-forum/kt-forum_img_user_admin.jpg
    default: https://res.cloudinary.com/dk7o7rlks/image/upload/v1725081005/kt-forum/kt-forum_img_user_default.jpg

  id:
    admin: kt-forum/kt-forum_img_user_admin
    default: kt-forum/kt-forum_img_user_default
